# Generated by Django 5.2.1 on 2025-05-26 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Crédito'), (2, 'Débito'), (3, 'Prepagada')])),
                ('banco', models.CharField(max_length=100)),
                ('ultimos_4_digitos', models.CharField(max_length=4)),
                ('mes_vencimiento', models.IntegerField()),
                ('anio_vencimiento', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile')),
            ],
        ),
    ]
