# Generated by Django 5.2.1 on 2025-05-26 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_paymentmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='rating',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('comida', 'Comida'), ('educacion', 'Educación'), ('ropa', 'Ropa'), ('otros', 'Otros')], max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.paymentmethod'),
        ),
    ]
