# Generated by Django 5.2.1 on 2025-05-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_challenge_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Comida', 'Comida'), ('Educación', 'Educación'), ('Ropa', 'Ropa'), ('Otros', 'Otros'), ('Ahorro', 'Ahorro')], max_length=50),
        ),
    ]
