# Generated by Django 5.2.1 on 2025-05-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='goal_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='type',
            field=models.CharField(choices=[('no_gastos', 'No gastar'), ('ahorro', 'Ahorro'), ('juego', 'Juego')], default='no_gastar', max_length=20),
        ),
    ]
