# Generated by Django 5.2.1 on 2025-05-28 04:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_userprofile_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='type',
            field=models.CharField(choices=[('no_gastos', 'No gastar'), ('ahorro', 'Ahorro')], default='no_gastar', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
