# Generated by Django 5.2.1 on 2025-05-28 04:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_challenge_type_alter_expense_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
