# Generated by Django 5.2.1 on 2025-05-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_preguntatrivia_puntajetrivia'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='trivia_puntaje',
            field=models.IntegerField(default=0),
        ),
    ]
