# Generated by Django 5.2.1 on 2025-05-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='sistema_de_pago',
            field=models.IntegerField(choices=[(1, 'Visa'), (2, 'Mastercard')], default=1),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Crédito'), (2, 'Débito')]),
        ),
    ]
