# Generated by Django 5.2.1 on 2025-06-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_paymentmethod_sistema_de_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Crédito'), (2, 'Débito')], default=1),
        ),
    ]
