# Generated by Django 5.2.1 on 2025-06-12 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_userprofile_is_blocked_userprofile_login_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(help_text='Describe el sorteo y premios')),
                ('fecha_sorteo', models.DateField(help_text='Fecha estimada del sorteo')),
                ('qr_yape', models.ImageField(upload_to='rifas/qr_yape/')),
                ('dni', models.CharField(max_length=15)),
                ('numero_celular', models.CharField(max_length=20)),
                ('foto_dni', models.ImageField(upload_to='rifas/foto_dni/')),
                ('selfie_con_dni', models.ImageField(upload_to='rifas/selfie_dni/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile')),
            ],
        ),
    ]
