# Generated by Django 5.2.1 on 2025-06-13 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_rifa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('dni', models.CharField(max_length=15)),
                ('celular', models.CharField(max_length=20)),
                ('numero_operacion', models.CharField(max_length=50)),
                ('metodo_pago', models.CharField(choices=[('yape', 'Yape'), ('plin', 'Plin')], max_length=20)),
                ('fecha_pago', models.DateField()),
                ('numero_rifa', models.IntegerField()),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rifa')),
            ],
        ),
    ]
