# Generated by Django 5.2.1 on 2025-06-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_participante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='numero_rifa',
            field=models.PositiveIntegerField(),
        ),
    ]
