# Generated by Django 5.2.1 on 2025-06-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_participante_numero_rifa'),
    ]

    operations = [
        migrations.AddField(
            model_name='rifa',
            name='foto_premio',
            field=models.ImageField(blank=True, null=True, upload_to='rifas/foto_premios/'),
        ),
    ]
