# Generated by Django 5.2.1 on 2025-06-20 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_rifa_foto_premio'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile'),
        ),
    ]
