# Generated by Django 5.2.1 on 2025-06-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_participante_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rifa',
            name='precio_numero',
            field=models.FloatField(default=0.0, help_text='Precio de cada número de rifa'),
        ),
    ]
