# Generated by Django 5.2.1 on 2025-06-27 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_rifa_precio_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='rifa',
            name='ganador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rifas_ganadas', to='myapp.participante'),
        ),
    ]
